version: '3.9'
services:
  api:
    build: .
    container_name: "collab-backend"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./CollabBackend/.env
    environment:
      - POSTGRES_DB=collab_development
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    depends_on:
      - db
  db:
    image: postgres
    container_name: "collab-postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=collab_development
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
volumes:
  postgres_data: