# Generated by Django 4.1.1 on 2023-05-09 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_owner'),
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.board'),
        ),
    ]
